### ISSUE TITLE
Does osc99 work?

### ISSUE THREAD

**Issue by pranavpa8788** [LuanVSO/pwsh-profile#2]
I had recently started using oh my posh and have been struggling to get the feature working where you open a new tab in windows terminal and it continues where you left off. 

I saw your issue https://github.com/JanDeDobbeleer/oh-my-posh/issues/724 and saw you mention osc99.

I've tried the same settings in my theme file (dracula) and also tried a copy of yours. However the new tab doesn't continue in the same directory as that of the previous tab

I'll be so grateful if you could provide any insight into this issue, thanks!

**Comment by LuanVSO** [comment]
i stopped using oh-my-posh as it added significant startup and prompt delay on my system.
(it was also kind of an overengineered  tool for what i needed it to do) so i rolled my own solution that is contained in this repo.
my solution does work correctly with osc9;9 and windows terminal:

https://user-images.githubusercontent.com/43626415/193971797-cdebc973-8a32-42b6-b573-3db0fc751d3c.mp4

**Comment by pranavpa8788** [comment]
Thanks for the clarification. Just curious, does it also work for duplicate tab? And can you add background color and stuff to your prompt?

**Comment by LuanVSO** [comment]
Yes it does work for duplicate tab, yes I can, the way that my prompt is configured is to have a list of powershell script blocks (referred to as lambdas in other languages) that returns strings, the script blocks are executed every prompt and the results are concatenated, so you can do anything on the prompt as long as you know your vt escape sequences

**Comment by pranavpa8788** [comment]
Thanks for letting me know man. I ended up writing a custom script solution for this problem anyways, since osc99 didn't work
